name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.15.1
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm -C packages/core install
      - run: pnpm -C packages/core lint
      - run: pnpm -C packages/core test
      - name: Guard against deep core imports
        run: |
          if rg -n "\.\./packages/core/src/" -S | grep -v "^packages/core/"; then
            echo "Deep imports into core src are forbidden. Use @minamorl/root-core barrel." >&2
            exit 1
          fi
